### ISSUE TITLE
Retour failing on redirects to external sites

### ISSUE THREAD

**Issue by jakebiesinger-onduo** [nystudio107/craft-retour#111]
Howdy! 

We have been using Retour to redirect to external pages (outside of our site). We recently upgraded to `"nystudio107/craft-retour": "3.1.35"` from `3.1.31` and suddenly these redirects are breaking w/an error 500.

Here's an example redirect that is currently failing for us:

![image](https://user-images.githubusercontent.com/50155347/78309550-1c17e800-7500-11ea-9791-e271ef7edfd3.png)

For this page, we're seeing the following error logs:

```
10.40.7.1 - - [02/Apr/2020:23:24:56 +0000] "GET /ifu/ HTTP/1.1" 500 19540 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"
==> /var/log/phperrors.log <==
[02-Apr-2020 19:24:56 America/New_York] PHP Fatal error: Uncaught TypeError: Argument 4 passed to craft\helpers\UrlHelper::siteUrl() must be of the type int or null, string given, called in /usr/share/nginx/html/vendor/nystudio107/craft-retour/src/services/Redirects.php on line 221 and defined in /usr/share/nginx/html/vendor/craftcms/cms/src/helpers/UrlHelper.php:288
Stack trace:
#0 /usr/share/nginx/html/vendor/nystudio107/craft-retour/src/services/Redirects.php(221): craft\helpers\UrlHelper::siteUrl('https:/storage....', NULL, NULL, '')
#1 /usr/share/nginx/html/vendor/nystudio107/craft-retour/src/services/Redirects.php(178): nystudio107\retour\services\Redirects->doRedirect('https://onduo.c...', '/ifu/', Array)
#2 /usr/share/nginx/html/vendor/nystudio107/craft-retour/src/Retour.php(514): nystudio107\retour\services\Redirects->handle404()
#3 [internal function]: nystudio107\retour\Retour->nystudio107\retour\{closure}(Object(craft\events\ExceptionEvent))
#4 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\ev in /usr/share/nginx/html/vendor/craftcms/cms/src/helpers/UrlHelper.php on line 288

```

**Comment by jakebiesinger-onduo** [comment]
Looks like this was fixed in `3.1.36`. I guess we'll have to be more thorough in our testing if this kind of failure can slip through your own.
