### ISSUE TITLE
Invalid Argument Error on /admin/retour/settings

### ISSUE THREAD

**Issue by davist11** [nystudio107/craft-retour#14]
After installing via the plugin store and visiting the settings page, I get the following error:

```
yii\base\InvalidArgumentException: Invalid path alias: @nystudio107/seomatic/assetbundles/seomatic/dist in /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/BaseYii.php:154
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/AssetManager.php(449): yii\BaseYii::getAlias('@nystudio107/se...')
#1 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/AssetManager.php(54): yii\web\AssetManager->publish('@nystudio107/se...')
#2 /Users/tdavis/sites/hamilton/vendor/nystudio107/craft-retour/src/controllers/SettingsController.php(74): craft\web\AssetManager->getPublishedUrl('@nystudio107/se...', true)
#3 [internal function]: nystudio107\retour\controllers\SettingsController->actionPluginSettings(Object(nystudio107\retour\models\Settings))
#4 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('plugin-settings', Array)
#7 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('plugin-settings', Array)
#8 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('retour/settings...', Array)
#9 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('retour/settings...', Array)
#10 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#11 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /Users/tdavis/sites/hamilton/public/index.php(46): yii\base\Application->run()
#13 {main}
```

Let me know if you need any other details, but seemed like just a copy and paste error that needed to be updated.

**Comment by khalwat** [comment]
ack! This is because you do not have SEOmatic installed... error on my part, I will fix it.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/releases/tag/3.0.0-beta.2
