### ISSUE TITLE
m181216_043222_rebuild_indexes failed on Craft 2 -> 3.6 migration

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-retour#155]
### Describe the bug

`m181216_043222_rebuild_indexes` seems to be failing with the following error during a Craft 2 migration:

```
drop index craft_idx_hljqqhopbhcmarbzohwfwbqotbcbvaiuoehq on {{%retour_static_redirects}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'craft_idx_hljqqhopbhcmarbzohwfwbqotbcbvaiuoehq'; check that column/key exists
The SQL being executed was: DROP INDEX `craft_idx_hljqqhopbhcmarbzohwfwbqotbcbvaiuoehq` ON `craft_retour_static_redirects
```

I have previously migrated a Craft 2 DB on <3.6 without this error many times. So I'm not sure if this specific to Craft CMS 3.6 as I can see this migration hasn't changed in 2 years and it is the only major update I can think of that might be causing this.

Full stacktrace during migration.

```
applying m181216_043222_rebuild_indexes
    > drop index craft_idx_hljqqhopbhcmarbzohwfwbqotbcbvaiuoehq on {{%retour_static_redirects}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'craft_idx_hljqqhopbhcmarbzohwfwbqotbcbvaiuoehq'; check that column/key exists
The SQL being executed was: DROP INDEX `craft_idx_hljqqhopbhcmarbzohwfwbqotbcbvaiuoehq` ON `craft_retour_static_redirects` (/app/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'DROP INDEX `cra...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('DROP INDEX `cra...')
#2 /app/vendor/yiisoft/yii2/db/Migration.php(507): yii\db\Command->execute()
#3 /app/vendor/nystudio107/craft-retour/src/migrations/m181216_043222_rebuild_indexes.php(70): yii\db\Migration->dropIndex('craft_idx_hljqq...', '{{%retour_stati...')
#4 /app/vendor/nystudio107/craft-retour/src/migrations/m181216_043222_rebuild_indexes.php(18): nystudio107\retour\migrations\m181216_043222_rebuild_indexes->dropIndexes()
#5 /app/vendor/craftcms/cms/src/db/Migration.php(52): nystudio107\retour\migrations\m181216_043222_rebuild_indexes->safeUp()
#6 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): craft\db\Migration->up()
#7 /app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(374): yii\console\controllers\BaseMigrateController->migrateUp('m181216_043222_...')
#8 [internal function]: craft\console\controllers\MigrateController->actionAll()
#9 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#11 /app/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('all', Array)
#12 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('all', Array)
#13 /app/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#14 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#15 /app/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#16 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /app/craft(24): yii\base\Application->run()
#18 {main}
*** failed to apply m181216_043222_rebuild_indexes (time: 0.002s)
```

### To reproduce

1. Craft 2 database with Retour installed
2. Run the migration track for the Craft 2 to 3 process (runs fine)
3. Install Craft 3 plugins and then run the migration track for plugins

### Expected behaviour

Should migrate the DB without any SQL error.

### Versions
- Plugin version: 3.1.45
- Craft version: 3.6.2

**Comment by jamesmacwhite** [comment]
Confirmed this is something related to Craft CMS 3.6, downgrading back to 3.5.19 the migration runs fine.

**Comment by khalwat** [comment]
Weird. Let me know if you uncover anything that's related to Retour. This is a very old migration, I'm confused as to why it would fail with Craft CMS 3.6 -- some input from Pixel & Tonic would be helpful.

**Comment by brandonkelly** [comment]
Just submitted PR #157 with a fix for this.

**Comment by khalwat** [comment]
You're amazing, thank you @brandonkelly

**Comment by khalwat** [comment]
Released in https://github.com/nystudio107/craft-retour/releases/tag/3.1.46

**Comment by jamesmacwhite** [comment]
Thank you both!
