### ISSUE TITLE
Batch importing redirects fails

### ISSUE THREAD

**Issue by PjGeeroms** [nystudio107/craft-retour#156]
### Describe the bug
After matching the columns and starting the import an error is thrown.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Retour"
2. Click on "Redirects"
3. Match the columns
4. Error is thrown: 
`Error: Call to undefined method League\Csv\Reader::setOffset() in /var/www/ordo/vendor/nystudio107/craft-retour/src/controllers/FileController.php:99
Stack trace:
#0 [internal function]: nystudio107\retour\controllers\FileController->actionImportCsvColumns()
#1 /var/www/ordo/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/ordo/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/ordo/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction(‘import-csv-colu...’, Array)
#4 /var/www/ordo/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction(‘import-csv-colu...’, Array)
#5 /var/www/ordo/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction(‘retour/file/imp...’, Array)
#6 /var/www/ordo/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction(‘retour/file/imp...’, Array)
#7 /var/www/ordo/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /var/www/ordo/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/ordo/web/index.php(25): yii\base\Application->run()
#10 {main}`

### Expected behaviour
The import is successful

### Versions
- Plugin version: 3.1.5
- Craft version: 3.5.16

**Comment by PjGeeroms** [comment]
Apparently after investigating some more it seems like something went wrong while installing the plugin.
It installed the new version for the csv reader but not the updated FileController.
