### ISSUE TITLE
Craft 2 migration m181013_171315_truncate_match_type fails with SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'hitLastTime' at row 1

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-retour#176]
### Describe the bug

This might be a very extreme edge case but somehow a redirect from a Craft CMS 2 DB managed to have the hitLastTime value of `0000-00-00 00:00:00` along with dateCreated and dateUpdated. Not entirely sure how. Resaving the entry in the Craft 2 DB seems to have updated the hitLastTime value to the save date, but dateCreated and dateUpdated remains at `0000-00-00 00:00:00`.

The fix is to either drop and create the redirects populating correct datetime values or modify them directly with an UPDATE query.

Just reporting in case there is anything that can be done in the migration itself to handle this, although I suspect an external process has changed not related to Retour.

```
*** applying m181013_171315_truncate_match_type
    > alter column redirectMatchType in table {{%retour_redirects}} to string(32) DEFAULT 'exactmatch' ... done (time: 0.126s)
    > alter column redirectMatchType in table {{%retour_static_redirects}} to string(32) DEFAULT 'exactmatch' ...Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'hitLastTime' at row 1
The SQL being executed was: ALTER TABLE `craft_retour_static_redirects` CHANGE `redirectMatchType` `redirectMatchType` varchar(32) DEFAULT 'exactmatch' (/app/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `cr...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('ALTER TABLE `cr...')
#2 /app/vendor/yiisoft/yii2/db/Migration.php(420): yii\db\Command->execute()
#3 /app/vendor/nystudio107/craft-retour/src/migrations/m181013_171315_truncate_match_type.php(50): yii\db\Migration->alterColumn('{{%retour_stati...', 'redirectMatchTy...', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /app/vendor/craftcms/cms/src/db/Migration.php(52): nystudio107\retour\migrations\m181013_171315_truncate_match_type->safeUp()
#5 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): craft\db\Migration->up()
#6 /app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(374): yii\console\controllers\BaseMigrateController->migrateUp('m181013_171315_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /app/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('all', Array)
#11 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('all', Array)
#12 /app/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#13 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#14 /app/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#15 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /app/craft(24): yii\base\Application->run()
#17 {main}
*** failed to apply m181013_171315_truncate_match_type (time: 0.220s)
```

**Comment by khalwat** [comment]
Weird. Appreciate the heads up, I'm going to call this an extreme edge case for now.
