### ISSUE TITLE
Undefined offset when saving entries (on non primary site)

### ISSUE THREAD

**Issue by davist11** [nystudio107/craft-retour#19]
We have a multi-site install. It looks like if we save an entry that is only available on a site that is not the primary site, we get an error:

```
yii\base\ErrorException: Undefined offset: 98356 in /storage/av05091/www/public_html/releases/20180914110132/vendor/nystudio107/craft-retour/src/Retour.php:444
Stack trace:
#0 /storage/av05091/www/public_html/releases/20180914110132/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/storage/av0509...', 444)
#1 /storage/av05091/www/public_html/releases/20180914110132/plugins/simplesentry/src/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/storage/av0509...', 444, Array)
#2 /storage/av05091/www/public_html/releases/20180914110132/plugins/simplesentry/src/vendor/sentry/sentry/lib/Raven/ErrorHandler.php(115): Raven_Breadcrumbs_ErrorHandler->handleError(8, 'Undefined offse...', '/storage/av0509...', 444, Array)
#3 /storage/av05091/www/public_html/releases/20180914110132/vendor/nystudio107/craft-retour/src/Retour.php(444): Raven_ErrorHandler->handleError(8, 'Undefined offse...', '/storage/av0509...', 444, Array)
#4 /storage/av05091/www/public_html/releases/20180914110132/vendor/nystudio107/craft-retour/src/Retour.php(285): nystudio107\retour\Retour->handleElementUriChange(Object(craft\elements\Entry))
#5 [internal function]: nystudio107\retour\Retour->nystudio107\retour\{closure}(Object(craft\events\ElementEvent))
#6 /storage/av05091/www/public_html/releases/20180914110132/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#7 /storage/av05091/www/public_html/releases/20180914110132/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent))
#8 /storage/av05091/www/public_html/releases/20180914110132/vendor/craftcms/cms/src/services/Elements.php(542): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent))
#9 /storage/av05091/www/public_html/releases/20180914110132/vendor/craftcms/cms/src/services/Elements.php(1395): craft\services\Elements->saveElement(Object(craft\elements\Entry), true, false)
#10 /storage/av05091/www/public_html/releases/20180914110132/vendor/craftcms/cms/src/services/Elements.php(500): craft\services\Elements->_propagateElement(Object(craft\elements\Entry), false, Array)
#11 /storage/av05091/www/public_html/releases/20180914110132/vendor/craftcms/cms/src/controllers/EntriesController.php(544): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#12 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#13 /storage/av05091/www/public_html/releases/20180914110132/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /storage/av05091/www/public_html/releases/20180914110132/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /storage/av05091/www/public_html/releases/20180914110132/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-entry', Array)
#16 /storage/av05091/www/public_html/releases/20180914110132/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#17 /storage/av05091/www/public_html/releases/20180914110132/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/save-en...', Array)
#18 /storage/av05091/www/public_html/releases/20180914110132/vendor/craftcms/cms/src/web/Application.php(541): craft\web\Application->runAction('entries/save-en...', Array)
#19 /storage/av05091/www/public_html/releases/20180914110132/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /storage/av05091/www/public_html/releases/20180914110132/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /storage/av05091/www/public_html/releases/20180914110132/public/index.php(46): yii\base\Application->run()
#22 {main}
```

Craft Pro 3.0.24
PHP 7.0.30
MySQL 5.7.23
Retour  3.0.4

**Comment by khalwat** [comment]
Will get this addressed ASAP

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/releases/tag/3.0.5
