### ISSUE TITLE
PHP error when using CLI command ./craft retour/stats/trim

### ISSUE THREAD

**Issue by croxton** [nystudio107/craft-retour#257]
### Describe the bug

PHP error thrown when trying to trim stats on the command line:

```
./craft retour/stats/trim
Trimming statistics
Exception 'Error' with message 'Typed property nystudio107\retour\console\controllers\StatsController::$limit must not be accessed before initialization'

in /[...]/[...]/[...]/[...]/vendor/nystudio107/craft-retour/src/console/controllers/StatsController.php:67

Stack trace:
#0 [internal function]: nystudio107\retour\console\controllers\StatsController->actionTrim()
#1  /[...]/[...]/[...]/[...]/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2  /[...]/[...]/[...]/[...]/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#3  /[...]/[...]/[...]/[...]/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('trim', Array)
#4  /[...]/[...]/[...]/[...]/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('trim', Array)
#5  /[...]/[...]/[...]/[...]/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('retour/stats/tr...', Array)
#6  /[...]/[...]/[...]/[...]/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('retour/stats/tr...', Array)
#7  /[...]/[...]/[...]/[...]/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('retour/stats/tr...', Array)
#8 /[...]/[...]/[...]/[...]/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#9  /[...]/[...]/[...]/[...]/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#10  /[...]/[...]/[...]/[...]/craft(23): yii\base\Application->run()
#11 {main}
```

### To reproduce
1. Run ./craft retour/stats/trim

### Versions
- Plugin version: 4.1.5
- Craft version: 4.3.1

**Comment by croxton** [comment]
Looks like you need to set a default value for $limit as it's a typed property: 

https://github.com/nystudio107/craft-retour/blob/1f576ebc20c2f860051c8a25576b300181e91316/src/console/controllers/StatsController.php#L33

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/25421a308fb49d2872322eb53f2c02c2beff1dde

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.6”,
```
Then do a `composer clear-cache && composer update`

**Comment by croxton** [comment]
Sorry, while that change prevents the PHP error being thrown, the stats are not actually trimmed.

It works if you set the default value to `0` instead of `null`:

```php
public ?int $limit = 0;
```

https://github.com/nystudio107/craft-retour/blob/558bdc59b21725b61f0ca5736f9d53362d08ba19/src/console/controllers/StatsController.php#L33

**Comment by khalwat** [comment]
That's strange, because `trimStatistics()` does this:

```php
    public function trimStatistics(int $limit = null): int
    {
        $affectedRows = 0;
        $db = Craft::$app->getDb();
        $quotedTable = $db->quoteTableName('{{%retour_stats}}');
        $limit = $limit ?? Retour::$settings->statsStoredLimit;
```

So if not specified, it should default to whatever your `statsStoredLimit` is set to. Maybe you need to set that to `0` in settings?

**Comment by croxton** [comment]
Sorry for not getting back sooner - you were right, it defaults to whatever you've set for `statsStoredLimit`.
