### ISSUE TITLE
3.2.17 breaks website: Exception 'ParseError' with message 'syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)'

### ISSUE THREAD

**Issue by lukasNo1** [nystudio107/craft-retour#307]
Happens on every request. I downgraded to 3.2.16 and it works again.

Craft 3.9.13

```
Exception 'ParseError' with message 'syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)'

in /var/www/backend/vendor/nystudio107/craft-retour/src/models/Settings.php:63

Stack trace:
#0 /var/www/backend/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/backen...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('nystudio107\\ret...')
#2 /var/www/backend/vendor/nystudio107/craft-retour/src/Retour.php(624): spl_autoload_call('nystudio107\\ret...')
#3 /var/www/backend/vendor/craftcms/cms/src/base/Plugin.php(186): nystudio107\retour\Retour->createSettingsModel()
#4 /var/www/backend/vendor/craftcms/cms/src/base/Plugin.php(197): craft\base\Plugin->getSettings()
#5 /var/www/backend/vendor/yiisoft/yii2/base/Component.php(180): craft\base\Plugin->setSettings(Array)
#6 /var/www/backend/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('settings', Array)
#7 /var/www/backend/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(nystudio107\retour\Retour), Array)
#8 /var/www/backend/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct(Array)
#9 /var/www/backend/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct('retour', Object(craft\console\Application), Array)
#10 /var/www/backend/vendor/nystudio107/craft-retour/src/services/ServicesTrait.php(64): craft\base\Plugin->__construct('retour', Object(craft\console\Application), Array)
#11 [internal function]: nystudio107\retour\Retour->__construct('retour', Object(craft\console\Application), Array)
#12 /var/www/backend/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#13 /var/www/backend/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('nystudio107\\ret...', Array, Array)
#14 /var/www/backend/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('nystudio107\\ret...', Array, Array)
#15 /var/www/backend/vendor/craftcms/cms/src/Craft.php(66): yii\BaseYii::createObject(Array, Array)
#16 /var/www/backend/vendor/craftcms/cms/src/services/Plugins.php(942): Craft::createObject(Array, Array)
#17 /var/www/backend/vendor/craftcms/cms/src/services/Plugins.php(232): craft\services\Plugins->createPlugin('retour', Array)
#18 /var/www/backend/vendor/craftcms/cms/src/base/ApplicationTrait.php(1520): craft\services\Plugins->loadPlugins()
#19 /var/www/backend/vendor/craftcms/cms/src/console/Application.php(48): craft\console\Application->_postInit()
#20 /var/www/backend/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#21 /var/www/backend/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#22 /var/www/backend/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#23 [internal function]: yii\console\Application->__construct(Array)
#24 /var/www/backend/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#25 /var/www/backend/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\console\\A...', Array, Array)
#26 /var/www/backend/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#27 /var/www/backend/vendor/craftcms/cms/src/Craft.php(66): yii\BaseYii::createObject(Array, Array)
#28 /var/www/backend/vendor/craftcms/cms/bootstrap/bootstrap.php(236): Craft::createObject(Array)
#29 /var/www/backend/vendor/craftcms/cms/bootstrap/console.php(51): require('/var/www/backen...')
#30 /var/www/backend/craft(19): require('/var/www/backen...')
#31 {main}

```

**Comment by khalwat** [comment]
Fixed in the above commit.

Released as `3.2.18` -> https://github.com/nystudio107/craft-retour/releases/tag/3.2.18
