### ISSUE TITLE
Exception when deleting site

### ISSUE THREAD

**Issue by sjelfull** [nystudio107/craft-retour#58]
Got this when deleting a site. Looks like Retour tries to get an element's url at a point where the site is already kind of deleted.

```
yii\base\Exception: Invalid site ID: 2 in /app/vendor/craftcms/cms/src/helpers/UrlHelper.php:232
Stack trace:
#0 /app/vendor/craftcms/cms/src/base/Element.php(1252): craft\helpers\UrlHelper::siteUrl('offline', NULL, NULL, 2)
#1 /app/vendor/nystudio107/craft-retour/src/Retour.php(295): craft\base\Element->getUrl()
#2 [internal function]: nystudio107\retour\Retour->nystudio107\retour\{closure}(Object(craft\events\ElementEvent))
#3 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#4 /app/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'beforeSaveEleme...', Object(craft\events\ElementEvent))
#5 /app/vendor/craftcms/cms/src/services/Elements.php(399): yii\base\Component->trigger('beforeSaveEleme...', Object(craft\events\ElementEvent))
#6 /app/vendor/craftcms/cms/src/services/Sections.php(1589): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#7 /app/vendor/craftcms/cms/src/services/Sections.php(776): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section))
#8 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(868): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#9 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#10 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#11 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(569): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#12 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(862): craft\services\ProjectConfig->processConfigChanges('sections.4588b6...')
#13 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#14 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#15 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(557): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#16 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(415): craft\services\ProjectConfig->processConfigChanges('sections.4588b6...', true)
#17 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(430): craft\services\ProjectConfig->set('sections.4588b6...', NULL)
#18 /app/vendor/craftcms/cms/src/services/Sections.php(925): craft\services\ProjectConfig->remove('sections.4588b6...')
#19 [internal function]: craft\services\Sections->pruneDeletedSite(Object(craft\events\DeleteSiteEvent))
#20 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\DeleteSiteEvent))
#21 /app/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterDeleteSite', Object(craft\events\DeleteSiteEvent))
#22 /app/vendor/craftcms/cms/src/services/Sites.php(1133): yii\base\Component->trigger('afterDeleteSite', Object(craft\events\DeleteSiteEvent))
#23 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(868): craft\services\Sites->handleDeletedSite(Object(craft\events\ConfigEvent))
#24 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#25 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#26 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(557): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#27 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(415): craft\services\ProjectConfig->processConfigChanges('sites.3df0ebb1-...', true)
#28 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(430): craft\services\ProjectConfig->set('sites.3df0ebb1-...', NULL)
#29 /app/vendor/craftcms/cms/src/services/Sites.php(1078): craft\services\ProjectConfig->remove('sites.3df0ebb1-...')
#30 /app/vendor/craftcms/cms/src/services/Sites.php(879): craft\services\Sites->deleteSite(Object(craft\models\Site), NULL)
#31 /app/vendor/craftcms/cms/src/controllers/SitesController.php(318): craft\services\Sites->deleteSiteById(2, NULL)
#32 [internal function]: craft\controllers\SitesController->actionDeleteSite()
#33 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#34 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#35 /app/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('delete-site', Array)
#36 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-site', Array)
#37 /app/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('sites/delete-si...', Array)
#38 /app/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('sites/delete-si...', Array)
#39 /app/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#40 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#41 /app/web/index.php(21): yii\base\Application->run()
#42 {main}
```

**Comment by khalwat** [comment]
Brad @ P&T contacted me about this -- he decided this was a Craft bug, because all Retour is doing is calling `craft\base\Element->getUrl()` which isn't supposed to throw any exceptions.
