### ISSUE TITLE
Regex errors in one link break all of Retour

### ISSUE THREAD

**Issue by jakebiesinger-onduo** [nystudio107/craft-retour#83]
Hi!

I recently imported ~200 regex links into Retour. One of them was missing a closing `)`, e.g., 

`^(?ifoobar/$` instead of
`^(?i)foobar/$`

Unfortunately, ALL my other Retour links broke. It would be nice to have these isolated. A malformed regex should only affect that redirect, not the entire Retour system.

Our marketing team has learned to add new links with much trepidation. plz fix :)

**Comment by khalwat** [comment]
Can you expand on what you mean by it breaking? What exactly happened?

**Comment by khalwat** [comment]
So testing it myself, it looks like it causes the function to throw an exception:

```
PHP Fatal Error – yii\base\ErrorException
Uncaught yii\base\ErrorException: preg_match(): Compilation failed: unrecognized character after (? or (?- at offset 4 in /home/vagrant/webdev/craft/craft-retour/src/services/Redirects.php:418
Stack trace:
#0 /home/vagrant/webdev/craft/craft-retour/src/services/Redirects.php(418): ::preg_match()
#1 /home/vagrant/webdev/craft/craft-retour/src/services/Redirects.php(301): nystudio107\retour\services\Redirects->resolveRedirect()
#2 /home/vagrant/webdev/craft/craft-retour/src/services/Redirects.php(177): nystudio107\retour\services\Redirects->findRedirectMatch()
#3 /home/vagrant/webdev/craft/craft-retour/src/Retour.php(514): nystudio107\retour\services\Redirects->handle404()
#4 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Event.php(312): nystudio107\retour\Retour->nystudio107\retour\{closure}()
#5 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Event.php(312): ::call_user_func:{/home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Event.php:312}()
#6 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Co
```

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-retour/commit/e1219dffa4ebddbf57d977080b7831aefc853524
